services:
  - type: web
    name: youtube-downloader
    env: python
    plan: free
    region: oregon
    buildCommand: |
      # Install the Chromium browser for headless browsing
      apt-get update
      apt-get install -y chromium-browser
      # Install Python dependencies
      pip install -r src/requirements.txt
    startCommand: uvicorn src.main:app --host=0.0.0.0 --port=8080
    autoDeploy: true
